// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"
	"database/sql"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (name, description, created_at, updated_at)
    VALUES ($1, $2, NOW(), NOW())
RETURNING
    id, name, description, created_at, updated_at, column_id
`

type CreateIssueParams struct {
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, createIssue, arg.Name, arg.Description)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ColumnID,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues
WHERE
    id = $1
`

func (q *Queries) DeleteIssue(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssue, id)
	return err
}

const getAllIssues = `-- name: GetAllIssues :many
SELECT
    id, name, description, created_at, updated_at, column_id
FROM
    issues
ORDER BY
    created_at DESC
`

func (q *Queries) GetAllIssues(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, getAllIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ColumnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT
    id, name, description, created_at, updated_at, column_id
FROM
    issues
WHERE
    id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ColumnID,
	)
	return i, err
}

const reassignIssuesFromColumn = `-- name: ReassignIssuesFromColumn :exec
UPDATE
    issues
SET
    column_id = $1
WHERE
    column_id = $2
`

type ReassignIssuesFromColumnParams struct {
	TargetColumn int64 `db:"target_column" json:"target_column"`
	SourceColumn int64 `db:"source_column" json:"source_column"`
}

func (q *Queries) ReassignIssuesFromColumn(ctx context.Context, arg ReassignIssuesFromColumnParams) error {
	_, err := q.db.ExecContext(ctx, reassignIssuesFromColumn, arg.TargetColumn, arg.SourceColumn)
	return err
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE
    issues
SET
    name = $2,
    description = $3,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, name, description, created_at, updated_at, column_id
`

type UpdateIssueParams struct {
	ID          int64          `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, updateIssue, arg.ID, arg.Name, arg.Description)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ColumnID,
	)
	return i, err
}
