// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/guregu/null"
)

type Conversation struct {
	ID        int64     `db:"id" json:"id"`
	UserID    int64     `db:"user_id" json:"user_id"`
	Title     string    `db:"title" json:"title"`
	Provider  string    `db:"provider" json:"provider"`
	Model     string    `db:"model" json:"model"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Issue struct {
	ID          int64       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
	CreatedAt   time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at" json:"updated_at"`
	ColumnID    int64       `db:"column_id" json:"column_id"`
}

type Message struct {
	ID             int64     `db:"id" json:"id"`
	ConversationID int64     `db:"conversation_id" json:"conversation_id"`
	Role           string    `db:"role" json:"role"`
	Content        string    `db:"content" json:"content"`
	SequenceNumber int32     `db:"sequence_number" json:"sequence_number"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}

type Project struct {
	ID        int64     `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	TeamID    int64     `db:"team_id" json:"team_id"`
}

type ProjectStatusColumn struct {
	ID            int64     `db:"id" json:"id"`
	ProjectID     int32     `db:"project_id" json:"project_id"`
	Name          string    `db:"name" json:"name"`
	PositionIndex int16     `db:"position_index" json:"position_index"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
}

type RefreshToken struct {
	ID        int64        `db:"id" json:"id"`
	UserID    int64        `db:"user_id" json:"user_id"`
	Jti       string       `db:"jti" json:"jti"`
	ExpiresAt time.Time    `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	RevokedAt sql.NullTime `db:"revoked_at" json:"revoked_at"`
}

type Team struct {
	ID          int64       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
	CreatedAt   time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at" json:"updated_at"`
}

type TeamMember struct {
	ID       int64     `db:"id" json:"id"`
	TeamID   int64     `db:"team_id" json:"team_id"`
	UserID   int64     `db:"user_id" json:"user_id"`
	JoinedAt time.Time `db:"joined_at" json:"joined_at"`
}

type TeamsLlmApiKey struct {
	ID           int64        `db:"id" json:"id"`
	TeamID       int64        `db:"team_id" json:"team_id"`
	Provider     string       `db:"provider" json:"provider"`
	EncryptedKey string       `db:"encrypted_key" json:"encrypted_key"`
	IsActive     sql.NullBool `db:"is_active" json:"is_active"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time    `db:"updated_at" json:"updated_at"`
	LastUsedAt   sql.NullTime `db:"last_used_at" json:"last_used_at"`
}

type User struct {
	ID           int64     `db:"id" json:"id"`
	Email        string    `db:"email" json:"email"`
	Name         string    `db:"name" json:"name"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}
